server:
  port: 8080

spring:
  config:
    import: "optional:file:.env[.properties]"
  application:
    name: backend
  datasource:
    url: ${DB_SOURCE}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


app:
  admin:
    password: ${ADMIN_PASSWORD}
    name: ${ADMIN_NAME}
    email: ${ADMIN_EMAIL}

jwt:
  signerKey: 5rSK2/ix9ATiI8r6hXO9bu95ElXbDVLCYMNBZZXTcdYdrrGZIVdv4T2gaJ93ZgYf

